"""warroom2.templates — persona file templates for the mount-new-agent wizard.

Each template is a plain ``str`` with ``{placeholder}`` slots that
``str.format(**ctx)`` fills in. Keep them small and opinionated — operators
can edit the resulting files post-apply.

Context keys used:
- ``slug``        — lowercase-dash agent id
- ``display``     — human display name
- ``model``       — sonnet | opus | haiku | gpt-5.5
- ``role``        — one-line role description from the wizard step 3
- ``today``       — ISO date string YYYY-MM-DD
- ``tools_md``    — already-rendered markdown bullet list of selected tools
"""

from __future__ import annotations

from typing import Dict, List

TEMPLATES: List[str] = ["default", "dev", "qa"]

ALLOWED_TOOLS: List[str] = ["bus", "paperclip", "trello", "bitbucket"]


_AGENTS_DEFAULT = """# {display} ({slug})

> Generated by the war-room 2.0 mount-agent wizard on {today}.

## Identity

You are **{display}**. Slug: `{slug}`. Model: `{model}`.

## Role

{role}

## Channels

- Telegram bot per `.env` (`{slug_upper}_TELEGRAM_TOKEN`).
- Agent bus journal at `/workspace/agent-bus/messages.ndjson`.

## Operating principles

1. Keep replies short. Default to one paragraph unless asked for a deep dive.
2. Never act destructively without explicit confirmation from the operator.
3. When uncertain, ask. When blocked, escalate to Captain via the bus.

See `SOUL.md` for tone and `TOOLS.md` for the tool surface you have access to.
"""

_AGENTS_DEV = """# {display} ({slug}) — Developer

> Generated by the war-room 2.0 mount-agent wizard on {today}.

## Identity

You are **{display}**, a developer agent. Slug: `{slug}`. Model: `{model}`.

## Role

{role}

## Day-to-day

- Pick up tickets from Paperclip / Trello / Jira (per `TOOLS.md`).
- Branch, code, test, push. Open PRs and wait for review.
- Prefer the smallest change that solves the problem. Cite files + line numbers.
- Mention `@captain` on the bus for cross-agent coordination.

## Guardrails

- Never push to `main` or `master` directly.
- Always run the local test suite before opening a PR.
- If a hook fails, fix the underlying issue — do not bypass.
"""

_AGENTS_QA = """# {display} ({slug}) — QA

> Generated by the war-room 2.0 mount-agent wizard on {today}.

## Identity

You are **{display}**, a QA agent. Slug: `{slug}`. Model: `{model}`.

## Role

{role}

## Day-to-day

- Watch the bus and PR queue for new work to verify.
- Write test plans before executing them.
- Report findings as structured bus messages: `{{level, summary, repro}}`.
- Block merges on critical findings; comment on PRs for non-critical ones.
"""

_SOUL_DEFAULT = """# {display} — Soul

Tone: calm, terse, helpful. No emoji unless the operator asks.
Voice: first-person singular. Never say "as an AI".
Defaults: concise, factual, link to source when possible.

When in doubt about scope, ask one clarifying question before acting.
"""


_TOOLS_HEADER = """# {display} — Tools

This file enumerates the integrations available to this agent. Edit freely.

"""


_TOOL_SNIPPETS: Dict[str, str] = {
    "bus": (
        "## Bus\n\n"
        "- Append to `/workspace/agent-bus/messages.ndjson` for cross-agent\n"
        "  comms. Use `bus-send.mjs` if available, otherwise direct ndjson\n"
        "  append with `{{ts, from, to, text}}`.\n"
    ),
    "paperclip": (
        "## Paperclip\n\n"
        "- Control plane at `http://paperclip:3100`. Use the `paperclip`\n"
        "  skill or HTTP API to check assignments, post comments, and\n"
        "  update task status.\n"
    ),
    "trello": (
        "## Trello\n\n"
        "- API key + token from `.env` (`TRELLO_API_KEY`, `TRELLO_API_TOKEN`).\n"
        "  Use for board/list/card CRUD against the Go-North workspace.\n"
    ),
    "bitbucket": (
        "## Bitbucket\n\n"
        "- Token from `.env` (`BITBUCKET_TOKEN`). Use for repo + PR CRUD.\n"
        "  Do not push to `main`/`master` without a PR.\n"
    ),
}


def _ctx(spec: Dict, today: str) -> Dict:
    slug = spec["slug"]
    return {
        "slug": slug,
        "slug_upper": slug.upper().replace("-", "_"),
        "display": spec["display_name"],
        "model": spec["model"],
        "role": spec.get("persona", {}).get("role", "").strip() or "TBD",
        "today": today,
    }


def render_agents_md(spec: Dict, today: str) -> str:
    template = spec.get("persona", {}).get("template", "default")
    if template == "dev":
        body = _AGENTS_DEV
    elif template == "qa":
        body = _AGENTS_QA
    else:
        body = _AGENTS_DEFAULT
    return body.format(**_ctx(spec, today))


def render_soul_md(spec: Dict, today: str) -> str:
    return _SOUL_DEFAULT.format(**_ctx(spec, today))


def render_tools_md(spec: Dict, today: str) -> str:
    tools = spec.get("persona", {}).get("tools", []) or []
    ctx = _ctx(spec, today)
    out = [_TOOLS_HEADER.format(**ctx)]
    if not tools:
        out.append("_No integrations selected. Edit this file to add them._\n")
    else:
        for t in tools:
            snippet = _TOOL_SNIPPETS.get(t)
            if snippet:
                out.append(snippet.format(**ctx))
                out.append("\n")
    return "".join(out)


def render_env_block(spec: Dict, token: str, today: str) -> str:
    ctx = _ctx(spec, today)
    return (
        f"\n# ── {ctx['display']} (added by wizard {today}) ──\n"
        f"{ctx['slug_upper']}_TELEGRAM_TOKEN={token}\n"
        f"{ctx['slug_upper']}_MODEL={ctx['model']}\n"
    )


def render_launch_line(spec: Dict) -> str:
    slug = spec["slug"]
    upper = slug.upper().replace("-", "_")
    return f'  "{slug}:{upper}_TELEGRAM_TOKEN:{spec["model"]}"\n'
